# Generated by Django 3.1.7 on 2021-03-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='First_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(help_text='Enter your memo', max_length=1000)),
                ('created', models.DateTimeField(auto_now=True)),
                ('first_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mynote.first_category')),
            ],
        ),
    ]
