# Generated by Django 3.1.7 on 2021-03-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0002_second_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='second_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mynote.second_category'),
        ),
    ]
