# Generated by Django 3.1.7 on 2021-03-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0003_note_second_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='second_category',
            old_name='cat1',
            new_name='first_cat',
        ),
        migrations.RemoveField(
            model_name='second_category',
            name='cat2',
        ),
    ]
