# Generated by Django 3.1.7 on 2021-03-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynote', '0005_second_category_second_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first_category',
            old_name='cat1',
            new_name='first_cat',
        ),
    ]
